# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "69fda8a554583f4dc6d1cd7edf761782"
name = "testing-address-change"
handle = "testing-address-change"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "macaronwork-dev1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_orders"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
